### ISSUE TITLE
How to gain the performance of Mask RCNN on Visible region?

### ISSUE THREAD

**Issue by zhixuanli** [YutingXiao/Amodal-Segmentation-Based-on-Visible-Region-Segmentation-and-Shape-Prior#3]
1. How to gain the performance of `Mask RCNN` on the `Visible` region?

2. And after training the method of `mask_rcnn_parallel_CtRef_VAR_SPRef_SPRet_FM_cocoacls_res50_SGD_1x`, which terms should be considered as the final result on the performance table? 

3. If the answer is `amodal ensemble` and `visible ensemble`, then where's the performance of `occluded area`?

Thanks again for your patience!

**Comment by YutingXiao** [comment]
1.python tools/train_net.py --config-file configs/mask_rcnn_R_50_FPN_1x_visible.yaml.

2.amodal2_segm(refined) and visible2_segm(refined)

3.Forget about amodal_ensemble. it is nothing. The information of metrics can be found in "Installation"

**Comment by YutingXiao** [comment]
If you use cocoapi in the detectron2/data/amodal_datasets/pycocotools. The APs,APm,APl correspnonds to the performance on occluded objects. s: occlusion rate 0.15, m: occlusion rate 0.25, l: occlusion rate 0.4.

By the way, it hard to define the mAP(Occluded) since your visible prediction and amodal prediction may not be the same even if the object is not occluded. The metrics for evaluate performance are different on different papers. My design may not be perfect.

**Comment by zhixuanli** [comment]
Thanks a lot!!
